# Generated by Django 5.0.4 on 2026-07-26 00:36

from django.db import migrations, models


def populate_card_ids(apps, schema_editor):
    StaffMember = apps.get_model('staff', 'StaffMember')
    for index, member in enumerate(StaffMember.objects.order_by('last_name', 'first_name', 'pk'), start=1):
        if not member.card_id:
            member.card_id = str(index)
            member.save(update_fields=['card_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffmember_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='card_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Номер на карточке'),
        ),
        migrations.RunPython(populate_card_ids, migrations.RunPython.noop),
    ]
