# Generated by Django 5.0.4 on 2026-03-16 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер дела')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок дела')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('sheets_count', models.PositiveIntegerField(default=0, verbose_name='Количество листов')),
                ('digitized', models.BooleanField(default=False, verbose_name='Оцифровано')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
                'ordering': ['inventory', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Номер фонда')),
                ('name', models.CharField(max_length=500, verbose_name='Название фонда')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_start', models.IntegerField(blank=True, null=True, verbose_name='Год начала')),
                ('date_end', models.IntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фонд',
                'verbose_name_plural': 'Фонды',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер описи')),
                ('name', models.CharField(max_length=500, verbose_name='Название описи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опись',
                'verbose_name_plural': 'Описи',
                'ordering': ['fund', 'number'],
            },
        ),
        migrations.CreateModel(
            name='FondItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('item_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ'), ('object', 'Предмет')], default='object', max_length=20, verbose_name='Тип')),
                ('period', models.CharField(blank=True, choices=[('1900-1930', '1900–1930'), ('1931-1940', '1931–1940'), ('1941-1945', '1941–1945 (Блокада)'), ('1946-1992', '1946–1992'), ('1992-2007', '1992–2007'), ('2007-now', '2007–настоящее время')], max_length=20, verbose_name='Период')),
                ('kp_number', models.CharField(blank=True, max_length=100, verbose_name='Номер по КП (книге поступлений)')),
                ('inventory_number', models.CharField(blank=True, max_length=100, verbose_name='Инвентарный номер')),
                ('goskatalog_number', models.CharField(blank=True, max_length=100, verbose_name='Номер в Госкаталоге')),
                ('size', models.CharField(blank=True, max_length=200, verbose_name='Размер')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Материал / техника')),
                ('creation_place', models.CharField(blank=True, max_length=200, verbose_name='Место создания')),
                ('creation_date_text', models.CharField(blank=True, max_length=200, verbose_name='Период создания (текст)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fond/items/', verbose_name='Фотография')),
                ('video_file', models.FileField(blank=True, help_text='MP4, WebM — загрузить файл', null=True, upload_to='fond/videos/', verbose_name='Видеофайл')),
                ('video_url', models.URLField(blank=True, help_text='Вставьте ссылку вместо загрузки файла', verbose_name='Ссылка на видео (YouTube/Vimeo)')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='fond.archivecase', verbose_name='Дело')),
            ],
            options={
                'verbose_name': 'Предмет фонда',
                'verbose_name_plural': 'Предметы фонда',
                'ordering': ['-created_at'],
            },
        ),
    ]
