# Generated by Django 5.0.4 on 2026-03-16 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fond', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonditem',
            name='linked_staff',
            field=models.ManyToManyField(blank=True, related_name='fond_items', to='staff.staffmember', verbose_name='Связанные сотрудники'),
        ),
        migrations.AddField(
            model_name='fonditem',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='fond.fund', verbose_name='Фонд'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='fond.fund', verbose_name='Фонд'),
        ),
        migrations.AddField(
            model_name='archivecase',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='fond.inventory', verbose_name='Опись'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('fund', 'number')},
        ),
    ]
