# Generated by Django 5.0.4 on 2026-04-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonditem',
            name='published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано'),
        ),
    ]
