# Generated by Django 6.0.5 on 2026-05-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond', '0003_alter_fonditem_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonditem',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='fond/items/', verbose_name='Оборотная сторона (для открыток)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='category',
            field=models.CharField(choices=[('documents', 'Документы и предметы'), ('photo', 'Фотодокументы'), ('personal', 'Личные фонды')], default='documents', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='fonditem',
            name='item_type',
            field=models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ'), ('object', 'Предмет'), ('postcard', 'Открытка')], default='object', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='fonditem',
            name='period',
            field=models.CharField(blank=True, choices=[('1880-1931', '1880–1931'), ('1931-1941', '1931–1941'), ('1941-1945', '1941–1945'), ('1945-1991', '1945–1991'), ('1991-2007', '1991–2007'), ('2007-now', '2007–н.д.')], max_length=20, verbose_name='Период'),
        ),
        migrations.CreateModel(
            name='FondItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fond/items/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fond.fonditem', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Медиафайл предмета',
                'verbose_name_plural': 'Медиафайлы предмета',
                'ordering': ['order'],
            },
        ),
    ]
