# Generated by Django 6.0.5 on 2026-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond', '0004_fonditem_back_image_fund_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='accession_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер книги поступлений'),
        ),
        migrations.AddField(
            model_name='fund',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='fund',
            name='pages_count',
            field=models.PositiveIntegerField(default=0, verbose_name='К-во страниц'),
        ),
    ]
