# Generated by Django 5.0.4 on 2026-07-25 17:05

import apps.fond.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond', '0005_fund_accession_number_fund_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonditem',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='fonditem',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='fonditem',
            name='display_layout',
            field=models.CharField(choices=[('standard', 'Обычная карточка'), ('postcard', 'Открытка: лицевая и оборот')], default='standard', max_length=20, verbose_name='Макет карточки'),
        ),
        migrations.AddField(
            model_name='fonditem',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место'),
        ),
        migrations.AddField(
            model_name='fonditem',
            name='metadata_template',
            field=models.JSONField(blank=True, default=apps.fond.models.default_fond_metadata_template, help_text='Ключи и значения отображаются в таблице карточки. Новые предметы создаются с пустым шаблоном.', verbose_name='Дополнительные поля макета'),
        ),
        migrations.AddField(
            model_name='fonditem',
            name='pages',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страницы'),
        ),
        migrations.AddField(
            model_name='fonditem',
            name='source',
            field=models.CharField(blank=True, max_length=300, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='fonditem',
            name='year',
            field=models.CharField(blank=True, max_length=100, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='fund',
            name='period',
            field=models.CharField(blank=True, choices=[('1880-1931', '1880–1931'), ('1931-1941', '1931–1941'), ('1941-1945', '1941–1945'), ('1945-1991', '1945–1991'), ('1991-2007', '1991–2007'), ('2007-now', '2007–н.д.')], help_text='Для личных фондов можно оставить пустым.', max_length=20, verbose_name='Исторический период'),
        ),
    ]
