# Generated by Django 5.0.4 on 2026-07-25 19:17

import django.db.models.deletion
from django.db import migrations, models


def _build_register_text(item):
    parts = []
    first_number = item.kp_number or item.inventory_number
    if first_number:
        parts.append(first_number)

    if item.archive_case_id and item.archive_case:
        inventory = item.archive_case.inventory
        if inventory:
            case_suffix = f'-{item.archive_case.number}' if item.archive_case.number else ''
            parts.append(f'Опись {inventory.number}{case_suffix}')

    if item.inventory_number and item.inventory_number != first_number:
        parts.append(item.inventory_number)

    if item.pages:
        parts.append(f'{item.pages} с.')

    return ' / '.join(parts)


def _build_detail_rows(item):
    inventory = item.archive_case.inventory if item.archive_case_id and item.archive_case else None
    inventory_value = ''
    if inventory:
        inventory_value = inventory.number
        if inventory.name:
            inventory_value = f'{inventory_value} ({inventory.name})'

    kp_value = item.inventory_number.replace('КП', '').strip() if item.inventory_number else item.kp_number
    return [
        ('Источник', item.source),
        ('Опись', inventory_value),
        ('Номер КП', kp_value),
        ('Дата поступления', item.acquisition_date.strftime('%d.%m.%y') if item.acquisition_date else ''),
        ('Датировка', item.year or item.creation_date_text),
        ('Материал', item.material),
        ('Размер', item.size),
        ('Аннотация', item.description),
    ]


def seed_fond_item_page_text(apps, schema_editor):
    FondItem = apps.get_model('fond', 'FondItem')
    FondItemDetailText = apps.get_model('fond', 'FondItemDetailText')

    for item in FondItem.objects.select_related('archive_case__inventory').all():
        register_text = _build_register_text(item)
        if register_text and not item.register_text:
            item.register_text = register_text
            item.save(update_fields=['register_text'])

        if FondItemDetailText.objects.filter(item=item).exists():
            continue

        FondItemDetailText.objects.bulk_create([
            FondItemDetailText(item=item, order=index, label=label, value=value)
            for index, (label, value) in enumerate(_build_detail_rows(item), start=1)
        ])


def unseed_fond_item_page_text(apps, schema_editor):
    FondItemDetailText = apps.get_model('fond', 'FondItemDetailText')
    FondItemDetailText.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fond', '0006_fonditem_acquisition_date_fonditem_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonditem',
            name='detail_path_text',
            field=models.CharField(blank=True, default='фонд >>> каталог', help_text='Текст слева под навигацией на странице предмета.', max_length=300, verbose_name='Путь в шапке страницы'),
        ),
        migrations.AddField(
            model_name='fonditem',
            name='empty_media_text',
            field=models.CharField(blank=True, default='MUSEUM', max_length=100, verbose_name='Текст вместо изображения'),
        ),
        migrations.AddField(
            model_name='fonditem',
            name='register_text',
            field=models.CharField(blank=True, help_text='Если оставить пустым, строка будет собрана из КП, описи, дела и страниц.', max_length=500, verbose_name='Учётная строка над заголовком'),
        ),
        migrations.CreateModel(
            name='FondItemDetailText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('label', models.CharField(max_length=120, verbose_name='Подпись')),
                ('value', models.TextField(blank=True, verbose_name='Текст')),
                ('visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_text_rows', to='fond.fonditem', verbose_name='Предмет фонда')),
            ],
            options={
                'verbose_name': 'Текстовая строка страницы предмета',
                'verbose_name_plural': 'Текстовые строки страницы предмета',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.RunPython(seed_fond_item_page_text, unseed_fond_item_page_text),
    ]
