# Generated by Django 5.0.4 on 2026-07-26 00:36

from django.db import migrations, models


def populate_inventories_count(apps, schema_editor):
    Fund = apps.get_model('fond', 'Fund')
    for fund in Fund.objects.all():
        fund.inventories_count = fund.inventories.count()
        fund.save(update_fields=['inventories_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('fond', '0007_fonditem_detail_path_text_fonditem_empty_media_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='inventories_count',
            field=models.PositiveIntegerField(default=0, help_text='Редактируемое число для строки "описей" на карточке фонда.', verbose_name='Описей на карточке'),
        ),
        migrations.RunPython(populate_inventories_count, migrations.RunPython.noop),
    ]
