# Generated by Django 5.0.4 on 2026-03-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('built_years', models.CharField(blank=True, max_length=100, verbose_name='Год постройки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('map_left', models.FloatField(default=10, verbose_name='Позиция слева (%)')),
                ('map_top', models.FloatField(default=10, verbose_name='Позиция сверху (%)')),
                ('map_width', models.FloatField(default=15, verbose_name='Ширина (%)')),
                ('map_height', models.FloatField(default=15, verbose_name='Высота (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('photos', models.ManyToManyField(blank=True, related_name='buildings', to='gallery.media', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания на карте',
                'ordering': ['order', 'name'],
            },
        ),
    ]
