# Generated by Django 5.0.4 on 2026-03-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0003_mapsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='map_clip_path',
            field=models.CharField(blank=True, default='', help_text='Необязательно. SVG polygon points в процентах, например: "0% 0%, 100% 0%, 100% 100%, 0% 100%" — прямоугольник. "0% 20%, 80% 0%, 100% 80%, 20% 100%" — трапеция. Оставьте пустым для стандартного прямоугольника.', max_length=500, verbose_name='Форма (clip-path polygon)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='map_rotation',
            field=models.FloatField(default=0, help_text='Поворот фигуры в градусах (0–360). Например, 45 — диагональ.', verbose_name='Угол поворота (°)'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='center_lat',
            field=models.FloatField(default=59.8228, help_text='Широта центра карты. Текущее значение: 59.8228', verbose_name='Центр — широта'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='center_lng',
            field=models.FloatField(default=30.3508, help_text='Долгота центра карты. Текущее значение: 30.3508', verbose_name='Центр — долгота'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='zoom',
            field=models.PositiveIntegerField(default=20, help_text='1 = весь мир, 20 = ~50м над землёй. Рекомендуется 18–20 для территории предприятия.', verbose_name='Zoom (масштаб)'),
        ),
    ]
