# Generated by Django 5.0.4 on 2026-03-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0004_alter_building_map_clip_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='map/buildings/', verbose_name='Главное фото'),
        ),
    ]
