# Generated by Django 5.0.4 on 2026-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0006_map_zoom_building_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsettings',
            name='center_lat',
        ),
        migrations.RemoveField(
            model_name='mapsettings',
            name='center_lng',
        ),
        migrations.AlterField(
            model_name='building',
            name='pos_x',
            field=models.FloatField(default=3684, help_text='X-координата центра здания на карте (0–7368)', verbose_name='Позиция X (пиксели)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='pos_y',
            field=models.FloatField(default=2072, help_text='Y-координата центра здания на карте (0–4144)', verbose_name='Позиция Y (пиксели)'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='building_zoom',
            field=models.IntegerField(default=1, help_text='Здания появляются на карте начиная с этого уровня масштабирования.', verbose_name='Zoom показа зданий'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='center_x',
            field=models.FloatField(default=3684, help_text='X-координата центра карты в пикселях изображения (0 = лево, 7368 = право).', verbose_name='Центр — X (пиксели)'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='center_y',
            field=models.FloatField(default=2072, help_text='Y-координата центра карты в пикселях изображения (0 = верх, 4144 = низ).', verbose_name='Центр — Y (пиксели)'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='max_zoom',
            field=models.IntegerField(default=3, help_text='Максимальный zoom (приближение).', verbose_name='Максимальный zoom'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='min_zoom',
            field=models.IntegerField(default=-2, help_text='Минимальный zoom (отрицательные = сильное отдаление).', verbose_name='Минимальный zoom'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='zoom',
            field=models.PositiveIntegerField(default=0, help_text='Начальный масштаб. 0 = вся карта видна, 1-2 = приближение.', verbose_name='Zoom (масштаб)'),
        ),
    ]
