# Generated by Django 5.0.4 on 2026-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0007_remove_mapsettings_center_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='zoom',
            field=models.FloatField(default=0, help_text='Начальный масштаб. Может быть отрицательным (отдаление) или десятичным (точность).', verbose_name='Zoom (масштаб)'),
        ),
    ]
