# Generated by Django 5.0.4 on 2026-04-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0008_alter_mapsettings_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsettings',
            name='show_territory',
            field=models.BooleanField(default=True, verbose_name='Показывать рамку территории'),
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='territory_h',
            field=models.FloatField(default=1500, verbose_name='Территория: Высота'),
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='territory_label',
            field=models.CharField(default='Территория комбината', max_length=100, verbose_name='Подпись территории'),
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='territory_w',
            field=models.FloatField(default=2000, verbose_name='Территория: Ширина'),
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='territory_x',
            field=models.FloatField(default=3684, verbose_name='Территория: Центр X'),
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='territory_y',
            field=models.FloatField(default=2072, verbose_name='Территория: Центр Y'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='building_zoom',
            field=models.FloatField(default=1, help_text='Здания появляются на карте начиная с этого уровня масштабирования.', verbose_name='Zoom показа зданий'),
        ),
    ]
