# Generated by Django 5.0.4 on 2026-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0009_mapsettings_show_territory_mapsettings_territory_h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsettings',
            name='territory_clip_path',
            field=models.CharField(blank=True, default='', help_text='Например: "0% 0%, 100% 0%, 100% 100%, 0% 100%"', max_length=500, verbose_name='Территория: Форма (clip-path polygon)'),
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='territory_rotation',
            field=models.FloatField(default=0, verbose_name='Территория: Поворот (°)'),
        ),
    ]
