# Generated by Django 5.0.4 on 2026-04-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0010_mapsettings_territory_clip_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsettings',
            name='show_territory_label',
            field=models.BooleanField(default=True, verbose_name='Показывать надпись территории'),
        ),
    ]
