# Generated by Django 5.0.4 on 2026-04-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0011_mapsettings_show_territory_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='map_clip_path',
            field=models.CharField(blank=True, default='', help_text='Необязательно. SVG polygon points в процентах, например: "0% 0%, 100% 0%, 100% 100%, 0% 100%" — прямоугольник. "0% 20%, 80% 0%, 100% 80%, 20% 100%" — трапеция. Оставьте пустым для стандартного прямоугольника.', max_length=2000, verbose_name='Форма (clip-path polygon)'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='territory_clip_path',
            field=models.CharField(blank=True, default='', help_text='Например: "0% 0%, 100% 0%, 100% 100%, 0% 100%"', max_length=2000, verbose_name='Территория: Форма (clip-path polygon)'),
        ),
    ]
