# Generated by Django 5.0.4 on 2026-04-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0012_alter_building_map_clip_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsettings',
            name='territory_mirror_x',
            field=models.BooleanField(default=False, verbose_name='Отразить по горизонтали'),
        ),
        migrations.AddField(
            model_name='mapsettings',
            name='territory_mirror_y',
            field=models.BooleanField(default=False, verbose_name='Отразить по вертикали'),
        ),
    ]
