# Generated by Django 5.0.4 on 2026-04-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0013_mapsettings_territory_mirror_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано'),
        ),
    ]
