# Generated by Django 5.0.4 on 2026-04-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0014_alter_building_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='manual_crop_data',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Данные обрезки'),
        ),
    ]
