# Generated by Django 5.0.4 on 2026-07-24 17:36

from django.db import migrations, models


def seed_lifestak_page(apps, schema_editor):
    Building = apps.get_model('mapblock', 'Building')
    try:
        building = Building.objects.get(slug='lifestak')
    except Building.DoesNotExist:
        return

    if not building.page_title:
        building.page_title = '«Лайв-стак»'
    if not building.page_subtitle:
        building.page_subtitle = '(корпус предубойного содержания скота)'
    if not building.built_years:
        building.built_years = '1931-1933'
    elif building.built_years == '1930–1932':
        building.built_years = '1931-1933'
    if not building.page_status:
        building.page_status = 'ОКН'
    if not building.page_description:
        building.page_description = (
            'Является важным звеном в технологической цепочке '
            'мясоперерабатывающего комплекса. В этом корпусе содержался перед '
            'убоем скот, откармливался, проходил ветеринарный осмотр. На 1 этаже '
            'здания находились ветеринарные службы и административные помещения. '
            'Остальные предназначались для содержания скота. Корпус оснащен '
            'специальным ступопандусом для подъема на этажи животных.'
        )
    building.save(update_fields=[
        'page_title',
        'page_subtitle',
        'built_years',
        'page_status',
        'page_description',
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0015_building_manual_crop_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='page_background',
            field=models.ImageField(blank=True, help_text='Если не указано, используется стандартный buildingBG.jpg.', null=True, upload_to='map/buildings/backgrounds/', verbose_name='Фон страницы здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='page_description',
            field=models.TextField(blank=True, help_text='Если пусто, используется основное описание здания.', verbose_name='Описание на странице здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='page_image',
            field=models.ImageField(blank=True, help_text='Основное фото для публичной страницы здания. Если не указано, используется главное фото.', null=True, upload_to='map/buildings/pages/', verbose_name='Фото на странице здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='page_status',
            field=models.CharField(blank=True, default='ОКН', max_length=100, verbose_name='Статус на странице'),
        ),
        migrations.AddField(
            model_name='building',
            name='page_subtitle',
            field=models.CharField(blank=True, help_text='Например: (корпус предубойного содержания скота).', max_length=500, verbose_name='Подзаголовок на странице'),
        ),
        migrations.AddField(
            model_name='building',
            name='page_title',
            field=models.CharField(blank=True, help_text='Например: «Лайв-стак». Если пусто, используется название здания.', max_length=300, verbose_name='Заголовок на странице'),
        ),
        migrations.RunPython(seed_lifestak_page, migrations.RunPython.noop),
    ]
