# Generated by Django 5.0.4 on 2026-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0016_building_page_background_building_page_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='page_background',
            field=models.ImageField(blank=True, help_text='Если не указано, используется стандартный buildingBG.webp.', null=True, upload_to='map/buildings/backgrounds/', verbose_name='Фон страницы здания'),
        ),
    ]
