# Generated by Django 5.0.4 on 2026-08-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapblock', '0018_mapsettings_territory_zoom_adjust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='page_background',
            field=models.ImageField(blank=True, help_text='Если не указано, используется стандартный buildingsPage.webp.', null=True, upload_to='map/buildings/backgrounds/', verbose_name='Фон страницы здания'),
        ),
    ]
