# Generated by Django 5.0.4 on 2026-03-16 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fond', '0002_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('period', models.CharField(choices=[('pre-soviet', 'Досоветский период (1900–1930)'), ('construction', 'Проектирование и строительство (1930–1933)'), ('prewar', 'Довоенный период (1933–1941)'), ('blockade', 'Блокадный период (1941–1944)'), ('golden', 'Период расцвета (1944–1992)'), ('post-soviet', 'Постсоветский период (1992–2007)'), ('modern', 'Современность (2007–н/д)')], max_length=30, verbose_name='Период')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='Обложка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['period', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Фотография'), ('video', 'Видео')], default='photo', max_length=10, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/photos/', verbose_name='Изображение')),
                ('video_file', models.FileField(blank=True, help_text='MP4, WebM, OGG — загрузить файл', null=True, upload_to='gallery/videos/', verbose_name='Видеофайл')),
                ('video_url', models.URLField(blank=True, help_text='Вставьте ссылку вместо загрузки файла', verbose_name='Ссылка на видео (YouTube/Vimeo)')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Подпись')),
                ('date_text', models.CharField(blank=True, max_length=100, verbose_name='Дата (текст)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='gallery.album', verbose_name='Альбом')),
                ('fond_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='fond.fonditem', verbose_name='Предмет фонда (оригинал)')),
                ('linked_staff', models.ManyToManyField(blank=True, related_name='photos', to='staff.staffmember', verbose_name='Изображённые / упомянутые сотрудники')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'ordering': ['album', 'order'],
            },
        ),
    ]
