# Generated by Django 6.0.5 on 2026-05-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond', '0003_alter_fonditem_published'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Период галереи',
                'verbose_name_plural': 'Периоды галереи',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Медиафайл', 'verbose_name_plural': 'Медиафайлы'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='period',
        ),
        migrations.AddField(
            model_name='album',
            name='is_newsreel',
            field=models.BooleanField(default=False, help_text='Если отмечено, альбом попадет в отдельную категорию', verbose_name='Кинохроника'),
        ),
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.TextField(blank=True, verbose_name='Описание (редактируемое)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='fond_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='fond.fonditem', verbose_name='Предмет фонда (ссылка на оригинал)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='Видеофайл'),
        ),
        migrations.AlterField(
            model_name='media',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube/Vimeo)'),
        ),
        migrations.AddField(
            model_name='album',
            name='gallery_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='gallery.galleryperiod', verbose_name='Период'),
        ),
    ]
