# Generated by Django 6.0.5 on 2026-05-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryperiod_alter_album_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='photographer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фотограф'),
        ),
        migrations.AlterField(
            model_name='media',
            name='date_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Год (текст)'),
        ),
    ]
