# Generated by Django 6.0.5 on 2026-05-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_media_photographer_alter_media_date_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryperiod',
            name='date_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='Годы (текст)'),
        ),
    ]
