# Generated by Django 5.0.4 on 2026-07-26 00:36

from django.db import migrations, models


def populate_gallery_card_fields(apps, schema_editor):
    GalleryPeriod = apps.get_model('gallery', 'GalleryPeriod')
    Album = apps.get_model('gallery', 'Album')
    Media = apps.get_model('gallery', 'Media')

    for index, period in enumerate(GalleryPeriod.objects.order_by('order', 'title', 'pk'), start=1):
        if not period.card_code:
            period.card_code = f'Г{index}'
            period.save(update_fields=['card_code'])

    for album in Album.objects.all():
        media_qs = Media.objects.filter(album=album, published=True)
        album.card_links_count = media_qs.count()
        album.card_photos_count = media_qs.filter(media_type='photo').count()
        album.save(update_fields=['card_links_count', 'card_photos_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galleryperiod_date_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='card_inventories_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Описей на карточке'),
        ),
        migrations.AddField(
            model_name='album',
            name='card_links_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ссылок на карточке'),
        ),
        migrations.AddField(
            model_name='album',
            name='card_photos_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Фотографий на карточке'),
        ),
        migrations.AddField(
            model_name='galleryperiod',
            name='card_code',
            field=models.CharField(blank=True, help_text='Например: Г1', max_length=20, verbose_name='Код на карточке'),
        ),
        migrations.RunPython(populate_gallery_card_fields, migrations.RunPython.noop),
    ]
