# Generated by Django 5.0.4 on 2026-08-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytextblock',
            name='font_family',
            field=models.CharField(choices=[('var(--font), Arial, sans-serif', 'TT Hoves (site default)'), ("'TT Hoves', sans-serif", 'TT Hoves (bundled website font)'), ('Arial, sans-serif', 'Arial'), ("'Arial Black', Gadget, sans-serif", 'Arial Black'), ("'Helvetica Neue', Helvetica, Arial, sans-serif", 'Helvetica'), ("'Segoe UI', Tahoma, Geneva, Verdana, sans-serif", 'Segoe UI'), ('Verdana, Geneva, sans-serif', 'Verdana'), ('Tahoma, Geneva, sans-serif', 'Tahoma'), ("'Trebuchet MS', Helvetica, sans-serif", 'Trebuchet MS'), ('Impact, Charcoal, sans-serif', 'Impact'), ("'Comic Sans MS', cursive, sans-serif", 'Comic Sans MS'), ('Georgia, serif', 'Georgia'), ("'Times New Roman', Times, serif", 'Times New Roman'), ('Garamond, serif', 'Garamond'), ("'Palatino Linotype', 'Book Antiqua', Palatino, serif", 'Palatino'), ('Cambria, Georgia, serif', 'Cambria'), ('Constantia, Georgia, serif', 'Constantia'), ("'Courier New', Courier, monospace", 'Courier New'), ("Consolas, 'Courier New', monospace", 'Consolas'), ("'Lucida Console', Monaco, monospace", 'Lucida Console')], default='var(--font), Arial, sans-serif', max_length=160, verbose_name='Шрифт'),
        ),
    ]
